[[main]]
name = "About"
url = "/#about"
weight = 2

[[main]]
name = "Contact"
url = "/contact/"
weight = 100

[[main]]
name = "Blog"
url = "/blog/"
weight = 60

[[main]]
name = "Engineering"
url = "/engineering/"
weight = 50
pre = "engineering"

[[main]]
name = "Contributions"
url = "/contributions/"
weight = 51
pre = "contributions"

